fprintf('Building installer package...\n');
fprintf('Time: %s\n\n', datestr(now));

exeDir = 'C:\chrysler\files\matlab files\AppDesigner\exe';
outDir = 'C:\chrysler\files\matlab files\AppDesigner\installer';
if ~exist(outDir,'dir'); mkdir(outDir); end

compiler.package.installer( ...
    fullfile(exeDir, 'ReactorDesignExplorer.exe'), ...
    fullfile(exeDir, 'requiredMCRProducts.txt'), ...
    'ApplicationName',  'Reactor Design Explorer', ...
    'RuntimeDelivery',  'web', ...
    'InstallerName',    'ReactorDesignExplorer_Setup', ...
    'Version',          '1.0', ...
    'OutputDir',        outDir);

fprintf('\nDone: %s\n', datestr(now));
d = dir(fullfile(outDir, '*.exe'));
for i = 1:numel(d)
    fprintf('%s  (%.0f MB)\n', d(i).name, d(i).bytes/1e6);
end
