fprintf('Starting compilation...\n');
fprintf('Time: %s\n\n', datestr(now));

mcc('-e', 'ReactorDesignExplorer.m', ...
    '-a', 'BatchReactorWindow.m', ...
    '-a', 'CSTRWindow.m', ...
    '-a', 'PFRWindow.m', ...
    '-a', 'ReactorCompareWindow.m', ...
    '-a', 'rxKinetics.m', ...
    '-a', 'rxWindowStyle.m', ...
    '-o', 'ReactorDesignExplorer', ...
    '-d', 'exe');

fprintf('\nCompilation complete: %s\n', datestr(now));
exeFile = fullfile('exe', 'ReactorDesignExplorer.exe');
if exist(exeFile, 'file')
    d = dir(exeFile);
    fprintf('Output: %s (%.1f MB)\n', exeFile, d.bytes/1e6);
else
    fprintf('WARNING: exe not found at expected path.\n');
    disp(dir('exe'));
end
